"""create case_events table

Revision ID: 0bba6352afc8
Revises: 498d00d2de5e
Create Date: 2026-08-26 23:08:44.367968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bba6352afc8'
down_revision: Union[str, Sequence[str], None] = '498d00d2de5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

casestate_enum = postgresql.ENUM(
    'new', 'pending_classification', 'classified', 'routed',
    'in_review', 'escalated', 'resolved', 'reopened',
    name='casestate',
    create_type=False
)

def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('case_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_state', casestate_enum, nullable=True),
    sa.Column('to_state', casestate_enum, nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_id'), 'case_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_events_id'), table_name='case_events')
    op.drop_table('case_events')
    # ### end Alembic commands ###
