"""create ai_classifications table

Revision ID: 1368496830e2
Revises: 1664f79aa456
Create Date: 2026-09-09 16:44:58.210892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '1368496830e2'
down_revision: Union[str, Sequence[str], None] = '1664f79aa456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

severity_enum = postgresql.ENUM('low', 'medium', 'high', 'critical', name='severity', create_type=False)
category_enum = postgresql.ENUM('fraud', 'prohibited_item', 'community_guideline', 'other', name='category', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('suggested_severity', severity_enum, nullable=True),
    sa.Column('suggested_category', category_enum, nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_classifications_id'), 'ai_classifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_classifications_id'), table_name='ai_classifications')
    op.drop_table('ai_classifications')
    # ### end Alembic commands ###
