"""add reported entity type, id, and reporter id to cases

Revision ID: 1664f79aa456
Revises: 3d7da5fda986
Create Date: 2026-09-03 00:15:04.022165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '1664f79aa456'
down_revision: Union[str, Sequence[str], None] = '3d7da5fda986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

reported_entity_type_enum = postgresql.ENUM(
    'listing', 'user', 'transaction', 'other',
    name='reportedentitytype'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    reported_entity_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('cases', sa.Column('reported_entity_type', sa.Enum('listing', 'user', 'transaction', 'other', name='reportedentitytype'), nullable=False))
    op.add_column('cases', sa.Column('reported_entity_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'reported_entity_id')
    op.drop_column('cases', 'reported_entity_type')
    # ### end Alembic commands ###
