"""add reporter_id to cases

Revision ID: 3d7da5fda986
Revises: 0bba6352afc8
Create Date: 2026-09-02 23:46:57.801228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7da5fda986'
down_revision: Union[str, Sequence[str], None] = '0bba6352afc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('reporter_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'reporter_id')
    # ### end Alembic commands ###
